---
title: "`r params$title`"
date: "`r params$generated_on`"
output:
  html_document:
    toc: true
    toc_depth: 2
    code_folding: hide
  pdf_document:
    toc: true
  word_document:
    toc: true
params:
  title: "Dynamic Analysis Report"
  generated_on: !r format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  logo: NULL
  analyses: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
library(knitr)
library(htmltools)
library(plotly)
library(sessioninfo)
```

```{r}
volcano_index <- sapply(params$analyses, function(analysis) {
  grepl(x = analysis$label,
        pattern = "volcano")
})

if(any(volcano_index)) {
  volcano_data <- params$analyses[volcano_index]
}

heatmap_index <- sapply(params$analyses, function(analysis) {
  grepl(x = analysis$label,
        pattern = "heatmap")
})

if(any(heatmap_index)) {
  heatmap_data <- params$analyses[heatmap_index]
}
```

# Analysis {.tabset}

```{r results='asis'}
if(any(heatmap_index)) {
  cat("## Heatmap\n\n")
}
```

```{r}
if(any(heatmap_index)) {
  l <- htmltools::tagList()
  for(a in 1:length(heatmap_data)) {
    names_settings <- names(heatmap_data[[a]]$settings)
    l[[a]] <- htmltools::tagList(
      htmltools::h2(heatmap_data[[a]]$label),
      htmltools::p("Settings:"),
      htmltools::tags$ul(
        lapply(names_settings, function(setting) {
          tags$li(paste0(setting, ": ", paste(heatmap_data[[a]]$settings[[setting]], collapse = ", ")))
        })
      ),
      heatmap_data[[a]]$plot |> 
        plotly::layout(height = 800)
    )
  }
  l
}
```

```{r results='asis'}
if(any(volcano_index)) {
  cat("## Volcano plot\n\n")
}
```

```{r}
if(any(volcano_index)) {
  l <- htmltools::tagList()
  for(a in 1:length(volcano_data)) {
    names_settings <- names(volcano_data[[a]]$settings)
    l[[a]] <- htmltools::tagList(
      htmltools::h2(volcano_data[[a]]$label),
      htmltools::p("Settings:"),
      htmltools::tags$ul(
        lapply(names_settings, function(setting) {
          tags$li(paste0(setting, ": ", paste(volcano_data[[a]]$settings[[setting]], collapse = ", ")))
        })
      ),
      volcano_data[[a]]$plot
    )
  }
  l
}
```

# Session info

```{r}
session_info()
```

